Milestone 1
billodiallo/newsweek2020 pull request #1
Opened 2021-01-25 15:51 UTC by billodiallo

working on :
- header
- navbar
- footer
- mobile sm
- tablet md

2021-01-25 16:40 UTC, Spayco approved these changes
# Milestone Approved ✔️ 

Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone.

- [ ] Make the nav matches the one in the original website ([Link to page](https://www.newsweek.com/)), make sure you match the spacing, borders, and layout 
- [ ] make the page centered and with space on the side, just like the original website ([Link to page](https://www.newsweek.com/))
- [ ] make the social icons on the footer on the left and `© 2021 NEWSWEEK DIGITAL LLC` next to the Logo, on mobile they will be each under the other. ([Link to page](https://www.newsweek.com/))
- [ ] Update the Live Demo link in your README.md
- [ ] Fix your linters.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-26 21:22 UTC, Spayco requested changes
# Invalid 🛑 

- [ ] in order to review the project, your linters needs to be fixed. (I know I reviewed the past milestone even though the linters are not fixed, but as of today repos needs to be fixed before a Code Reviewer can review a project/milestone)


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-27 18:02 UTC, Spayco approved these changes
# Milestone Approved ✔️ 

Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone.

**General**
- [ ] Fix the colors in the website and make it match the original website

**Tablet**
- [ ] The right section (Debate, Opinion, etc...) just disappears on the right side of the page, and I can see it when I scroll there. it should instead be at the bottom after the other 2 sections

**Mobile**

- [ ] Make sure you follow the right order for mobile

<table>
    <tbody>
        <tr>
            <td>TOP STORY</th>
        </tr>
        <tr>
            <td>FEATURED STORIES</th>
        </tr>
        <tr>
            <td>THE DEBATE</th>
        </tr>
        <tr>
            <td>OPINION</th>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</th>
        </tr>
        <tr>
            <td>MORE STORIES</th>
        </tr>
        <tr>
            <td>LATEST NEWS</th>
        </tr>
        <tr>
            <td>MY TURN</th>
        </tr>
        <tr>
            <td>CULTURE & TRAVEL</th>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</th>
        </tr>
        <tr>
            <td>FREE SIGN UP</th>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</th>
        </tr>
    </tbody>
</table>

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    display: flex;
- [ ] Use `d-flex` Bootstrap class instead of this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    text-align: center;
- [ ] Use `text-align-center` Bootstrap class instead of this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    position: absolute;
- [ ] Use `position-absolute` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    flex-direction: column;
- [ ] Use  `flex-direction-column` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    text-align: center;
- [ ] Use `text-align-center` Bootstrap class instead of this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  padding-right: 0;
- [ ] Use `pr-0` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  display: flex;
- [ ] Use `d-flex` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  position: absolute;
- [ ] Use `position-absolute` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  align-items: center;
- [ ] Use `align-items-center` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +} */
- [ ] Remove commented code

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  padding: 0;
- [ ] use `m-0` and `p-0` Bootstrap classes for these.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  padding-left: 0;
- [ ] Use `pl-0` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  display: flex;
- [ ] Use `d-flex` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  position: absolute;
- [ ] Use `position-absolute` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  display: flex;
- [ ] Use `d-flex` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  justify-content: center;
- [ ] Use `justify-content-center` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    display: flex;
- [ ] Use `d-flex` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    flex-direction: column;
- [ ] Use `flex-direction-column` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    align-items: center;
- [ ] Use `align-items-center` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    justify-content: center;
- [ ] - [ ] Use `justify-content-center` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +    flex-direction: column;
- [ ] - [ ] Use `flex-direction-column` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  align-items: center;
- [ ] - [ ] Use `align-items-center` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, SpaYco commented on styles/style.css
> +  border-radius: 50%;
- [ ] Use `rounded-circle` Bootstrap class for this.

2021-01-27 18:02 UTC, Spayco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, Spayco commented on styles/style.css
> +  font-weight: bold;
- [ ] Use `font-weight-bold` Bootstrap class for this.

2021-01-27 18:02 UTC, Spayco commented on styles/style.css
> +  font-weight: bold;
- [ ] Use `font-weight-bold` Bootstrap class for this.

2021-01-27 18:02 UTC, Spayco commented on styles/style.css
> +  position: fixed;
- [ ] Use `position-fixed` Bootstrap class for this.

2021-01-27 18:02 UTC, Spayco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, Spayco commented on styles/style.css
> +  position: relative;
- [ ] Use `position-relative` Bootstrap class for this.

2021-01-27 18:02 UTC, Spayco commented on styles/style.css
> +  font-weight: bolder;
- [ ] Use `font-weight-bolder` Bootstrap class for this.

2021-01-27 20:17 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] the Subscribe / Newsletter sections aren't there, please fix them
- [ ] check my comments above in the previous reviews to fix the CSS properties that can be turned into bootstrap classes, make sure to double-check in case I miss some.

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-28 15:57 UTC, billodiallo commented
-TABLET and Large screen fixed.

ordered in Mobile 

TOP STORY
--
FEATURED STORIES
THE DEBATE
OPINION
SPONSORED INSIGHT
MORE STORIES
LATEST NEWS
MY TURN
CULTURE & TRAVEL
SPONSORED INSIGHT
FREE SIGN UP
SPONSORED INSIGHT

--MATCHING COLORS like original.
-- changed some CSS code using  bootstrap

2021-01-28 19:32 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] The navbar is smaller than the rest of the page, make them equal
- [ ] you still have a lot of CSS properties that can be turned into bootstrap classes, please fix **all** the ones I mentioned above, I can see that only 3 of what I mentioned got fixed.

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-29 11:34 UTC, billodiallo commented
Dear @Spayco 
We fixed the navbar issue and change CSS code that are changeable in to bootstrap, the rest if it affect all the page and give more time for debugging. Thanks for your review.

2021-01-29 16:42 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @ . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 
- [ ] Branch name should be descriptive and meaningful, please edit the branch name and update the PR with the new branch name, DO NOT close the PR and open a new one USE THE SAME PR just update the branch name. Example of good branch name: `newsweek-clone`
- [ ] The issues still persisnt on the navbar
![image](https://user-images.githubusercontent.com/25774518/106300853-95659180-621c-11eb-9d23-aebd85ac0f0f.png)
- [x] The logo on the footer doesn't match original
![image](https://user-images.githubusercontent.com/25774518/106301299-29cff400-621d-11eb-8c3e-15653c2e16d5.png)
- [ ] Editors Pick section should change to a two column layout on tablet view
![image](https://user-images.githubusercontent.com/25774518/106301552-761b3400-621d-11eb-84ae-0363ba2ff394.png)
- [ ] Navbar z-index should be fix so this doesn't happen
![image](https://user-images.githubusercontent.com/25774518/106301735-ae227700-621d-11eb-8745-4b15681d0912.png)
![image](https://user-images.githubusercontent.com/25774518/106301779-c09cb080-621d-11eb-84da-bfc3bf00983b.png)
- [ ] Alignment of the text
![image](https://user-images.githubusercontent.com/25774518/106301874-ddd17f00-621d-11eb-9efc-ab878a0218d2.png)
- [ ] Use bootstrap classes instead of custom CSS rules. Review previous inline observations in `style.css` file and remove rules that have a bootstrap class counterpart.
  - [ ] text decoration
  - [ ] text color
  - [ ] display
  - [ ] position
  - [ ] text transform
  - [ ] font weight bold
  - [ ] text decoration
  - [ ] text align
  - [ ] flex direction
  - [ ] align items
  - [ ] justify content
  - [ ] padign right 0

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

<div>
  <div style="width:50px; height: 50px" align="center">
    <a href="https://avatars.githubusercontent.com/u/25774518?s=400&u=ae20ddf2d6fb3cae9e2f4044afe3b93d19e5b69e&v=4" alt="Julio Añoveros" title="@jubaan" width="100px" heigh="100px">
    </a>
  </div>
  </br>
  <p align="center">
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
  <p align="center">
    <b>Feel stuck?</b></br>
    First breath... just do it.</br>
    Take 15-20 min away from the computer,</br>
    stretch, meditate, do some exercise, drink water,</br>
    or do whatever is necessary to distract your mind</br> 
    from the obstacle.</br></br> 
    Sometimes you just need to get away</br>
    to see things with a new perspetive.
  </p>
  <p align="center">
    <b>Need help?</b></br>
    Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack,</br>
    you'll find me as @jubaan.
  </p>
  </br>
  <p align="center">
    <q>A <b>great programer</b> is not the one that knows it all,</br>
    but the one that ask a lot of question.</q></br></br>
    <b>Don't hesitate to ask for help!</b>
  </p>
</div>

2021-01-29 18:39 UTC, closed without merging